# Generated by Django 4.1 on 2022-08-06 22:46

import api.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("release_date", models.DateField()),
                (
                    "release_type",
                    models.CharField(
                        choices=[
                            ("LP", "LP"),
                            ("Single", "Single"),
                            ("Compilation", "Compilation"),
                            ("EP", "EP"),
                            ("Live", "Live Album"),
                            ("Remix", "Remix"),
                            ("Soundtrack", "Soundtrack"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "art_cover",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        max_length=255,
                        null=True,
                        quality=90,
                        scale=None,
                        size=[750, 750],
                        upload_to=api.models.RenameImageToSlug("album/art_covers/"),
                    ),
                ),
                (
                    "art_cover_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField()),
            ],
        ),
    ]
