# Generated by Django 4.1 on 2022-08-07 16:28

import api.helpers.RenameImageToSlug
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("full_name", models.CharField(max_length=255, null=True)),
                ("birth_date", models.DateField(null=True)),
                ("death_date", models.DateField(null=True)),
                (
                    "bg_image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        max_length=255,
                        null=True,
                        quality=90,
                        scale=None,
                        size=[1920, 1080],
                        upload_to=api.helpers.RenameImageToSlug.RenameImageToSlug(
                            "artist/bg_images/"
                        ),
                    ),
                ),
                ("bg_image_url", models.URLField(max_length=2048, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("founding_year", models.IntegerField(max_length=4, null=True)),
                ("breakup_year", models.IntegerField(max_length=4, null=True)),
                (
                    "bg_image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        max_length=255,
                        null=True,
                        quality=90,
                        scale=None,
                        size=[1920, 1080],
                        upload_to=api.helpers.RenameImageToSlug.RenameImageToSlug(
                            "artist/bg_images/"
                        ),
                    ),
                ),
                ("bg_image_url", models.URLField(max_length=2048, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="album",
            name="art_cover",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                max_length=255,
                null=True,
                quality=90,
                scale=None,
                size=[720, 720],
                upload_to=api.helpers.RenameImageToSlug.RenameImageToSlug(
                    "album/art_covers/"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="art_cover_url",
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="artist_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="api.artist"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="band_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="api.band"
            ),
        ),
    ]
