# Generated by Django 4.1 on 2022-08-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_type",
            field=models.CharField(
                choices=[
                    ("LP", "LP"),
                    ("Single", "Single"),
                    ("Compilation", "Compilation"),
                    ("EP", "EP"),
                    ("Live", "Live Album"),
                    ("Remix", "Remix"),
                    ("Soundtrack", "Soundtrack"),
                    ("Other", "Other"),
                ],
                default="LP",
                max_length=11,
            ),
        ),
    ]
