# Generated by Django 4.1 on 2022-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_artist_band_alter_album_art_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="breakup_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="band",
            name="founding_year",
            field=models.IntegerField(null=True),
        ),
    ]
