# Generated by Django 4.1 on 2022-08-14 17:50

import api.helpers.RenameImageToSlug
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_alter_genre_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_text", models.TextField()),
                (
                    "profile_picture",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        max_length=255,
                        null=True,
                        quality=90,
                        scale=None,
                        size=[500, 500],
                        upload_to=api.helpers.RenameImageToSlug.RenameImageToSlug(
                            "profile_picture/"
                        ),
                    ),
                ),
                ("profile_picture_url", models.URLField(max_length=2048, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contributor",
                "verbose_name_plural": "Contributors",
            },
        ),
    ]
