# Generated by Django 4.1 on 2022-08-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_track"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.artist"
                    ),
                ),
                (
                    "band_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.band"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_author_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_featured_author",
                        to="api.track",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_author_updated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
