# Generated by Django 4.1 on 2022-08-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_featuredauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredauthor",
            name="artist_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.artist"
            ),
        ),
        migrations.AlterField(
            model_name="featuredauthor",
            name="band_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.band"
            ),
        ),
    ]
