# Generated by Django 4.1 on 2022-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_bandmember_join_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(related_name="album_genres", to="api.genre"),
        ),
        migrations.DeleteModel(
            name="AlbumGenre",
        ),
    ]
