# Generated by Django 4.1 on 2022-08-27 22:26

import api.helpers.RenameImageToSlug
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_album_genres_delete_albumgenre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="art_cover",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WebP",
                keep_meta=True,
                max_length=255,
                null=True,
                quality=90,
                scale=None,
                size=[720, 720],
                upload_to=api.helpers.RenameImageToSlug.RenameImageToSlug("album/"),
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="bg_image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WebP",
                keep_meta=True,
                max_length=255,
                null=True,
                quality=90,
                scale=None,
                size=[1920, 1080],
                upload_to=api.helpers.RenameImageToSlug.RenameImageToSlug("artist/"),
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="bg_image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WebP",
                keep_meta=True,
                max_length=255,
                null=True,
                quality=90,
                scale=None,
                size=[1920, 1080],
                upload_to=api.helpers.RenameImageToSlug.RenameImageToSlug("band/"),
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="about_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="profile_picture",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WebP",
                keep_meta=True,
                max_length=255,
                null=True,
                quality=90,
                scale=None,
                size=[500, 500],
                upload_to=api.helpers.RenameImageToSlug.RenameImageToSlug(
                    "profile_picture/"
                ),
            ),
        ),
    ]
