# Generated by Django 4.1.1 on 2022-09-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_album_art_cover_alter_artist_bg_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="disc",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
