# Generated by Django 4.1.1 on 2022-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_track_disc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="position",
            field=models.PositiveIntegerField(),
        ),
    ]
